// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function DeleteFile(arg1:string,arg2:string):Promise<boolean>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteShell(arg1:string,arg2:string):Promise<string>;

export function GetDeviceInfo(arg1:string):Promise<main.DeviceInfoResponse>;

export function GetDevices():Promise<Array<main.Device>>;

export function GetInstalledApps(arg1:string,arg2:boolean):Promise<Array<string>>;

export function GetProcesses(arg1:string):Promise<Array<main.ProcessInfo>>;

export function GetSettings():Promise<config.AppConfig>;

export function GetStoragePoints(arg1:string):Promise<Array<string>>;

export function KillProcess(arg1:string,arg2:string):Promise<string>;

export function ListFiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<main.FileEntry>>;

export function SaveSettings(arg1:config.AppConfig):Promise<string>;

export function StartMirroring(arg1:string):Promise<string>;
